#ifndef PICO_MSG_TYPES_H_
#define PICO_MSG_TYPES_H_

#define MSU_PROTO_TCP_HANDSHAKE 100
#define MSU_PROTO_TCP_HANDSHAKE_RESPONSE 101
#define MSU_PROTO_TCP_CONN_RESTORE 102
#define MSU_PROTO_TCP_ROUTE_HS_REQUEST 103

#define MSU_PROTO_PICO_TCP_STACK 500
#define MSU_PROTO_PICO_TCP_APP_ECHO 501

#endif
