#ifndef MSU_IDS_H_
#define MSU_IDS_H_

#define SOCKET_MSU_TYPE_ID 10
#define TEST_MSU_TYPE_ID 100
#define WEBSERVER_READ_MSU_TYPE_ID 500
#define WEBSERVER_HTTP_MSU_TYPE_ID 552
#define WEBSERVER_REGEX_MSU_TYPE_ID 553
#define WEBSERVER_WRITE_MSU_TYPE_ID 554
#define WEBSERVER_REGEX_ROUTING_MSU_TYPE_ID 560

#endif
